'use client';

import DeveloperFeatures from "@/components/developer-section/developer-section";
import FeaturesGrid from "@/components/feature-grid/feature-grid";
import TradersSection from "@/components/traders-section/traders-section";
import type { NextPage } from "next";
import Head from "next/head";
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Liquidbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Group 8665.png" />
      </Head>
      <div className="w-full max-w-screen-2xl mx-auto min-h-[calc(70vh)] bg-cover bg-center text-gray-900 dark:text-white flex items-center justify-center">
        <div>
          <h3 className='text-2xl text-center mt-[50px]'>Welcome to Liquidbook</h3>
          <div className='relative'>
            <Image src="/liquid-2.png" width={220} height={400} alt="icon" className='overflow-hidden absolute -top-[80px] -left-[120px] z-1' ></Image>
            <h1 className='md:text-7xl text-center mt-[40px] z-5 text-5xl'>The Most Capital Efficient <br />Order Book DEX</h1>
            <p className="text-xl mt-[50px] text-center font-extralight">Secure, Transparent, and Lightning-Fast <br />Harness the Power of Decentralization for Seamless Trade Execution</p>
          </div>
          <div className='absolute right-0 top-[350px] overflow-hidden'>
            <Image src="/liquid.png" width={350} height={350} alt="icon" className='overflow-hidden' ></Image>
          </div>
        </div>
      </div>
      <div className="w-full mx-auto min-h-[calc(100vh)] bg-cover bg-center text-gray-900 dark:text-white flex items-center justify-center sm:py-8 lg:py-6">
        <FeaturesGrid />
      </div>
      <div>
        <TradersSection />
      </div>
      <div>
        <DeveloperFeatures />
      </div>
    </main>
  );
};

export default Home;